import { Main, Head, NextScript, Html } from "next/document";
import React from "react";
import Footer from "../Components/Footer";
import Navbar from "../Components/Navbar";

export default function _document() {
    return(
        <React.Fragment>
            <Html >
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <body>
                    <Navbar/>
                    <Main />
                    <NextScript />
                    <Footer/>
                </body>
            </Html>
        </React.Fragment>
    )
}