name: Deploy to GitHub Pages


on:
  push:
    branches: [main]
    



jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
     
      - name: Install packages
        run: npm ci
        working-directory: "./portfolio-web-frontend"
      - name: Build project
        run: npm run build
        working-directory: "./portfolio-web-frontend"
      - name: Export static files
        run: npm run export
        working-directory: "./portfolio-web-frontend"
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
        working-directory: "./portfolio-web-frontend"
      - name: adds CNAME file 
        run : touch "xandrfdev.com" CNAME
        working-directory: "./portfolio-web-frontend"

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './portfolio-web-frontend/out'
          destination-github-username: 'xandrf'
          destination-repository-name: 'xandrf.github.io'
          user-email: xandrf@xandrfdev.com
          target-branch: main